.gitmodules, solx/src/process/mod.rs, solx/src/solx/arguments.rs, solx/tests/cli/recursive_process.rs
Shows contract path in `--recursive-process`.
It helps to debug when one translation unit's process hangs.
=> fix: show contract path in --recursive-process

README.md
Given that we use them, it's better to make it clear.
=> chore: add acknowledgement for solc

solx/src/const.rs, solx/src/process/mod.rs, solx/src/solx/main.rs
Fixes the stack limit that was regressed during migration to one-process-per-translation-unit approach.
=> fix: sets the stack limit back to 64 MB

Cargo.lock, solx-solc/Cargo.toml, solx-standard-json/Cargo.toml, solx-standard-json/src/input/mod.rs, solx-yul/Cargo.toml, solx/Cargo.toml, solx/src/build/contract/object.rs, solx/src/build/mod.rs, solx/src/project/contract/mod.rs, solx/tests/cli/version.rs
Makes a few fixes in compilation of LLVM IR through standard JSON.
=> fix: LLVM IR standard JSON

.github/workflows/deploy-docs.yaml, .github/workflows/release.yaml
Default `GITHUB_TOKEN` does not trigger any workflows for release generation. As we shouldn't use any private tokens, try to use `workflow_call` to trigger documentation update.
=> ci: deploy docs after successful release by workflow call

docs/src/02-command-line-interface.md, solx-solc/src/lib.rs, solx-standard-json/src/input/settings/selection/mod.rs, solx-standard-json/src/input/settings/selection/selector.rs, solx/src/lib.rs, solx/src/solx/arguments.rs, solx/src/solx/main.rs, solx/tests/cli/mod.rs, solx/tests/cli/no_import_callback.rs, solx/tests/common/mod.rs
Supports the `--no-import-callback` parameter.
It is passed by Hardhat, that manages import resolution by itself.
=> feat: add the --no-import-callback flag

solx-solc/src/lib.rs
Fixes the solc's `solidity_compiler` foreign function signature.
It wasn't matching its solc counterpart.
=> fix: solc solidity_compiler foreign function signature

.gitmodules, Cargo.lock, docs/src/02-command-line-interface.md, docs/src/03-standard-json.md, solx-standard-json/src/input/settings/selection/selector.rs, solx-standard-json/src/output/contract/evm/bytecode.rs, solx-standard-json/src/output/contract/evm/mod.rs, solx/Cargo.toml, solx/src/build/contract/mod.rs, solx/src/build/contract/object.rs, solx/src/build/mod.rs, solx/src/lib.rs, solx/src/process/input.rs, solx/src/process/mod.rs, solx/src/project/contract/mod.rs, solx/src/project/mod.rs, solx/src/solx/arguments.rs, solx/src/solx/main.rs, solx/tests/cli/asm.rs, solx/tests/common/mod.rs, solx/tests/unit/optimizer.rs, solx/tests/unit/standard_json.rs
Optionally etrieves EVM assembly from LLVM.
It is required for the integration with Compiler Explorer.
=> feat: support LLVM-EVM assembly

README.md
We have broken links to some old builds as part of our installation instructions, but they point to the Releases page anyway. 
I suggest just removing the links to the Builds related to the solx_demo.
- [N/A] Tests for the changes have been added / updated.
- [N/A] Documentation comments have been added / updated.
- [N/A] Code has been formatted via `cargo fmt` and checked with `cargo clippy`.
=> docs: update README.md to remove dead links in installation instructions.

Cargo.lock, solx-yul/Cargo.toml, solx-yul/src/yul/lexer/token/lexeme/keyword.rs, solx-yul/src/yul/parser/error.rs, solx-yul/src/yul/parser/statement/block.rs, solx-yul/src/yul/parser/statement/code.rs, solx-yul/src/yul/parser/statement/function_definition.rs, solx-yul/src/yul/parser/statement/mod.rs, solx-yul/src/yul/parser/statement/object.rs, solx-yul/src/yul/parser/statement/switch/case.rs, solx-yul/src/yul/parser/statement/switch/mod.rs, solx-yul/src/yul/parser/statement/variable_declaration.rs, solx/src/project/contract/ir/yul.rs, solx/src/yul/parser/statement/function_definition.rs, solx/tests/cli/yul.rs, solx/tests/common/const.rs, solx/tests/data/contracts/yul/ObjectNaming.yul
1. Removes the requirement for Yul objects to be naming strictly as pairs with a `_deployed` suffix (e.g. `Contract`/`Contract_deployed`). Now runtime code is detected solely by its position in solc Yul output.
2. Removes `object` and `code` from reserved keywords similarly to how `data` has been handled. Now all 3 are treated as identifiers according to the Yul spec.
Resolves https://github.com/matter-labs/solx/issues/61
=> fix: Yul object naming assumptions and keywords

Cargo.lock, docs/src/03-standard-json.md, solx-standard-json/src/input/settings/optimizer.rs, solx/src/project/contract/mod.rs
`-Oz` mode is not ready yet, and sometimes leads to issues such as OOMs and infinite loops.
=> fix: turn off size fallback by default

.github/workflows/release.yaml
Mark only official tag releases as latest.
We don't want to change `latest` label for temporary manually created releasees.
=> ci: mark only official tag releases as latest

.github/workflows/release.yaml
Update auto-changelog generation.
To automatically generate changelog from the latest release to a new one ignoring intermediate manual releases if any.
=> chore: update auto-changelog generation

.github/forge-benchmarks.toml, .github/workflows/foundry-benchmarks.yaml, .gitmodules, Cargo.lock, Cargo.toml, docs/src/02-command-line-interface.md, docs/src/03-standard-json.md, solx-solc/src/lib.rs, solx-standard-json/src/input/settings/optimizer/mod.rs, solx-standard-json/src/output/error/mod.rs, solx/src/build/contract/mod.rs, solx/src/build/mod.rs, solx/src/error/mod.rs, solx/src/error/stack_too_deep.rs, solx/src/lib.rs, solx/src/solx/main.rs, solx/tests/cli/debug_output_dir.rs, solx/tests/cli/mod.rs, solx/tests/cli/optimization.rs, solx/tests/cli/optimization_size_fallback.rs
Adds environment variables for solx-specific CLI and standard JSON parameters:
1. `SOLX_DEBUG_OUTPUT_DIR`: allows dumping LLVM IR and other IRs while using toolkits such as Foundry or Hardhat.
2. `EVM_DISABLE_MEMORY_SAFE_ASM_CHECK`: disables the stack-too-deep/unsafe-assembly showstopper when the user knows what they are doing. 
3. `SOLX_OPTIMIZATION`: allows setting the optimization level while using toolkits such as Foundry or Hardhat.
4. `SOLX_OPTIMIZATION_SIZE_FALLBACK`: allows enabling the size optimization fallback while using toolkits such as Foundry or Hardhat.
solx will be mostly used from upstream Foundry and Hardhat. They cannot pass arbitrary parameters to solx, so this solution will temporarily unlock the full power that we can provide at the moment.
=> feat: support env-vars for solx-specific parameters

solx-evm-assembly/src/ethereal_ir/function/block/mod.rs
Uses an ordered `BTreeSet` for EVM assembly block predecessors.
`HashSet` causes indeterministic output in debug mode.
=> fix: make EVMLA block predecessors ordered again

Cargo.lock, docs/src/02-command-line-interface.md, solx/src/build/contract/mod.rs, solx/src/build/mod.rs
Unhardcodes some `--output-directory` file extensions.
=> chore: unhardcode remaining file extensions that mimic solc

.github/forge-benchmarks.toml
Adds more projects for benchmarking:
1. morpho-blue
2. lido-core (turned off because written in solc v0.4)
=> ci: add more Foundry projects for benchmarking

docs/src/02-command-line-interface.md, solx-standard-json/src/input/mod.rs, solx/tests/cli/debug_output_dir.rs
Introduces an env var for dumping of standard JSON input.
It is useful for debugging and benchmarking of large projects.
=> feat: add an env var to dump input JSON

.gitmodules, Cargo.lock, solx/tests/cli/standard_json.rs, solx/tests/common/const.rs, solx/tests/data/standard_json_input/solidity_fuzzed_simple_use_expression.json
Fixes https://github.com/matter-labs/solx/issues/136
=> fix: don't rematerialize CALLDATALOAD when it redefines a VR

Cargo.lock, Cargo.toml, README.md, solx-llvm-builder/Cargo.toml, solx-llvm-builder/LICENSE-APACHE, solx-llvm-builder/LICENSE-MIT, solx-llvm-builder/src/build_type.rs, solx-llvm-builder/src/ccache_variant.rs, solx-llvm-builder/src/lib.rs, solx-llvm-builder/src/llvm_path.rs, solx-llvm-builder/src/llvm_project.rs, solx-llvm-builder/src/lock.rs, solx-llvm-builder/src/platforms/aarch64_linux_gnu.rs, solx-llvm-builder/src/platforms/aarch64_macos.rs, solx-llvm-builder/src/platforms/mod.rs, solx-llvm-builder/src/platforms/shared.rs, solx-llvm-builder/src/platforms/x86_64_linux_gnu.rs, solx-llvm-builder/src/platforms/x86_64_macos.rs, solx-llvm-builder/src/platforms/x86_64_windows_gnu.rs, solx-llvm-builder/src/sanitizer.rs, solx-llvm-builder/src/solx_llvm_builder/arguments.rs, solx-llvm-builder/src/solx_llvm_builder/main.rs, solx-llvm-builder/src/utils.rs
1. Migrates the https://github.com/matter-labs/era-compiler-llvm-builder to this repo.
2. Removes MUSL and experimental targets.
3. Fixes an issue where all targets had been built instead of just selected ones.
4. Makes tests of the original repo redundant, as the tool gonna be black-box tested while building solx in all workflows.
There is an ongoing migration of all solx code to this monorepo.
=> chore: migrates the LLVM builder to this monorepo
